local_costmap:
  local_costmap:
    ros__parameters:
      use_sim_time: True
      global_frame: odom
      robot_base_frame: base_link
      update_frequency: 10.0
      publish_frequency: 5.0
      rolling_window: true
      width: 40
      height: 40
      resolution: 0.05
      footprint: "[[0.25, 0.24], [0.25, -0.24], [-0.25, -0.24], [-0.25, 0.24]]"
      footprint_padding: 0.05

      plugins: ["lane_layer", "obstacle_layer", "inflation_layer"]

      lane_layer:
        plugin: "nav2_costmap_2d::StaticLayer"
        map_topic: /perception/road_costmap
        map_subscribe_transient_local: True
        subscribe_to_updates: True
        use_maximum: True
        track_unknown_space: False

      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        observation_sources: scan
        scan:
          topic: /scan
          max_obstacle_height: 2.0
          clearing: True
          marking: True
          data_type: LaserScan

      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        inflation_radius: 0.3
        cost_scaling_factor: 3.0